# retornar aluno
import requests

url = "https://app.redacaonline.com.br/api/students"

payload={}
headers = {
  'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxMzIiLCJqdGkiOiI1MTNhMDdhMDdmMmY4OTI5MWUyMzQ5MTVmMDY5ODIyYWZhNjkxZDAwZGQ2YzZiNjVkM2IyMmY1N2QwNzNmZTEzN2NhMjMxZDc1MmQwMTg3YSIsImlhdCI6MTczNzA1Mjk4Ny40MTIwNDgsIm5iZiI6MTczNzA1Mjk4Ny40MTIwNTIsImV4cCI6MTg5NDgxOTM4Ny40MDM0MDcsInN1YiI6IjMxOSIsInNjb3BlcyI6WyIqIl19.UP9ThFiYOvtjr2JOQuu0nSWzroOz6WmWCnfNK4yhU-j_02pcDT1hukXrgV_FnsCqy37kGgAZVXT-uk2TLr8RWxMww4JXtqLDCdH6uSmQvO2uK1HAutxkoJNFDurIjTcfX2RmbQ4_TD0QUc2pyyHZ9lB9C4nOlOvRLkJIOoyGAa3gUlTHgX8GN5x2ZS_2bxrYPy4ioFDMNTwCi5UG_fXbApmVuXvhc35muacC1TVmuExvGQLpliDsZqNNJgZSVZsqdhFQS4ZrqYMz-pkd0_W0AuCSYxjMKyEAjcd6aEQfkLiGfVzI0EJ19e1Yc-vBG1SxC4Iv7FfhL6H9hahMZ-sQK07Ilbt9vD7k-I-93vvHBmlYIT4A4wC9QqH-z-I0hg64JjYsPLBezqmZOUEmcsan30OFZSlSp2iRkgd4iEnvia41KdkllERkoPPu5o4fq8hQ6dfVvGsqSQ0ZdMRWy0ukWTdAvgExFCh3i7Q6hadvdePrSzNUIrESp4tKpTg5qtVtbaseZNz7IkzpuYbk8tJUolNIterF20nc0leBbk2Qx0cjrrw6Cyzu7AElUxG-vALI5FRmR9jsWT_knrSQaWZaRo1tHrCF0yG19odOjS8Scd-97JTzN-gStji6XyDl5fTQV0uljHS3CqyTFDcWl9ZRk3wI5ITjFgYaiVEIkZ7U5p4'
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)

### Response
# {
#   "current_page": 1,
#   "data": [
#     {
#       "id": 611602,
#       "class_id": 32245,
#       "name": "BEATRIZ VALENTIM SANTOS DOS REIS",
#       "email": "beatrizvalentim51@gmail.com",
#       "cpf": null,
#       "address_number": null,
#       "address_cep": null,
#       "address_complement": null,
#       "address": null,
#       "neighborhood": null,
#       "city": null,
#       "state": null,
#       "birthdate": null,
#       "mobile": null,
#       "phone": null,
#       "external_id": "41504812",
#       "created_at": "2024-06-20T12:17:07.000000Z",
#       "deleted_at": null,
#       "is_med": false
#     },
#     {
#       "id": 611603,
#       "class_id": 32245,
#       "name": "CATHARINA COSTA FREITAS",
#       "email": "catharina.cfreitas12@gmail.com",
#       "cpf": null,
#       "address_number": null,
#       "address_cep": null,
#       "address_complement": null,
#       "address": null,
#       "neighborhood": null,
#       "city": null,
#       "state": null,
#       "birthdate": null,
#       "mobile": null,
#       "phone": null,
#       "external_id": "171800182",
#       "created_at": "2024-06-20T12:17:08.000000Z",
#       "deleted_at": null,
#       "is_med": false
#     },
#     {
#       "id": 611604,
#       "class_id": 32245,
#       "name": "EDUARDO MENEZES CAMPILLAY ALVES",
#       "email": "edu.menezes2572@gmail.com",
#       "cpf": null,
#       "address_number": null,
#       "address_cep": null,
#       "address_complement": null,
#       "address": null,
#       "neighborhood": null,
#       "city": null,
#       "state": null,
#       "birthdate": null,
#       "mobile": null,
#       "phone": null,
#       "external_id": "141600133",
#       "created_at": "2024-06-20T12:17:09.000000Z",
#       "deleted_at": null,
#       "is_med": false
#     },
#     {
#       "id": 611605,
#       "class_id": 32245,
#       "name": "GABRIEL VIANNA LEITÃO",
#       "email": "gabrielviannaleitao@gmail.com",
#       "cpf": null,
#       "address_number": null,
#       "address_cep": null,
#       "address_complement": null,
#       "address": null,
#       "neighborhood": null,
#       "city": null,
#       "state": null,
#       "birthdate": null,
#       "mobile": null,
#       "phone": null,
#       "external_id": "31500040",
#       "created_at": "2024-06-20T12:17:10.000000Z",
#       "deleted_at": null,
#       "is_med": false
#     },
#     {
#       "id": 611606,
#       "class_id": 32245,
#       "name": "GABRIELA CASTRO JERZAK VEL DOBOSZ",
#       "email": "gabriela.castrojvd38@gmail.com",
#       "cpf": null,
#       "address_number": null,
#       "address_cep": null,
#       "address_complement": null,
#       "address": null,
#       "neighborhood": null,
#       "city": null,
#       "state": null,
#       "birthdate": null,
#       "mobile": null,
#       "phone": null,
#       "external_id": "11602838",
#       "created_at": "2024-06-20T12:17:11.000000Z",
#       "deleted_at": null,
#       "is_med": false
#     },
#     {
#       "id": 611607,
#       "class_id": 32245,
#       "name": "GUILHERME DE CASTRO RAMOS",
#       "email": "guilhermedecastroramos5@gmail.com",
#       "cpf": null,
#       "address_number": null,
#       "address_cep": null,
#       "address_complement": null,
#       "address": null,
#       "neighborhood": null,
#       "city": null,
#       "state": null,
#       "birthdate": null,
#       "mobile": null,
#       "phone": null,
#       "external_id": "31400630",
#       "created_at": "2024-06-20T12:17:11.000000Z",
#       "deleted_at": null,
#       "is_med": false
#     },
#     {
#       "id": 611608,
#       "class_id": 32245,
#       "name": "IGOR DE LIMA MARQUES",
#       "email": "igor.il652112@gmail.com",
#       "cpf": null,
#       "address_number": null,
#       "address_cep": null,
#       "address_complement": null,
#       "address": null,
#       "neighborhood": null,
#       "city": null,
#       "state": null,
#       "birthdate": null,
#       "mobile": null,
#       "phone": null,
#       "external_id": "161802502",
#       "created_at": "2024-06-20T12:17:12.000000Z",
#       "deleted_at": null,
#       "is_med": false
#     },
#     {
#       "id": 611609,
#       "class_id": 32245,
#       "name": "ÍTALO BRITO ALCÂNTARA",
#       "email": "italobritoalcantara2006@gmail.com",
#       "cpf": null,
#       "address_number": null,
#       "address_cep": null,
#       "address_complement": null,
#       "address": null,
#       "neighborhood": null,
#       "city": null,
#       "state": null,
#       "birthdate": null,
#       "mobile": null,
#       "phone": null,
#       "external_id": "11301309",
#       "created_at": "2024-06-20T12:17:13.000000Z",
#       "deleted_at": null,
#       "is_med": false
#     },
#     {
#       "id": 611610,
#       "class_id": 32245,
#       "name": "JOÃO PEDRO PINHEIRO CRUZ",
#       "email": "jppinheiro.cruz@yahoo.com.br",
#       "cpf": null,
#       "address_number": null,
#       "address_cep": null,
#       "address_complement": null,
#       "address": null,
#       "neighborhood": null,
#       "city": null,
#       "state": null,
#       "birthdate": null,
#       "mobile": null,
#       "phone": null,
#       "external_id": "172300788",
#       "created_at": "2024-06-20T12:17:14.000000Z",
#       "deleted_at": null,
#       "is_med": false
#     },
#     {
#       "id": 611611,
#       "class_id": 32245,
#       "name": "JÚLIA OLIVEIRA BENEVIDES",
#       "email": "juliaoliveira.cherry@gmail.com",
#       "cpf": null,
#       "address_number": null,
#       "address_cep": null,
#       "address_complement": null,
#       "address": null,
#       "neighborhood": null,
#       "city": null,
#       "state": null,
#       "birthdate": null,
#       "mobile": null,
#       "phone": null,
#       "external_id": "141200157",
#       "created_at": "2024-06-20T12:17:15.000000Z",
#       "deleted_at": null,
#       "is_med": false
#     },
#     {
#       "id": 611612,
#       "class_id": 32245,
#       "name": "JULIANA TEIXEIRA DE LIMA",
#       "email": "teixeiradelimajuliana@gmail.com",
#       "cpf": null,
#       "address_number": null,
#       "address_cep": null,
#       "address_complement": null,
#       "address": null,
#       "neighborhood": null,
#       "city": null,
#       "state": null,
#       "birthdate": null,
#       "mobile": null,
#       "phone": null,
#       "external_id": "142200472",
#       "created_at": "2024-06-20T12:17:16.000000Z",
#       "deleted_at": null,
#       "is_med": false
#     },
#     {
#       "id": 611613,
#       "class_id": 32245,
#       "name": "LAILA ROCHA GRIMALDI RIZZO",
#       "email": "lailarochalpo@gmail.com",
#       "cpf": null,
#       "address_number": null,
#       "address_cep": null,
#       "address_complement": null,
#       "address": null,
#       "neighborhood": null,
#       "city": null,
#       "state": null,
#       "birthdate": null,
#       "mobile": null,
#       "phone": null,
#       "external_id": "151502284",
#       "created_at": "2024-06-20T12:17:17.000000Z",
#       "deleted_at": null,
#       "is_med": false
#     },
#     {
#       "id": 611614,
#       "class_id": 32245,
#       "name": "LUISA APARECIDA BARBOSA FRAGA",
#       "email": "luisabfraga@gmail.com",
#       "cpf": null,
#       "address_number": null,
#       "address_cep": null,
#       "address_complement": null,
#       "address": null,
#       "neighborhood": null,
#       "city": null,
#       "state": null,
#       "birthdate": null,
#       "mobile": null,
#       "phone": null,
#       "external_id": "62400555",
#       "created_at": "2024-06-20T12:17:17.000000Z",
#       "deleted_at": null,
#       "is_med": false
#     },
#     {
#       "id": 611615,
#       "class_id": 32245,
#       "name": "LUIZ OTÁVIO DOMINGUES MARQUES",
#       "email": "lomarques2006@gmail.com",
#       "cpf": null,
#       "address_number": null,
#       "address_cep": null,
#       "address_complement": null,
#       "address": null,
#       "neighborhood": null,
#       "city": null,
#       "state": null,
#       "birthdate": null,
#       "mobile": null,
#       "phone": null,
#       "external_id": "140900438",
#       "created_at": "2024-06-20T12:17:18.000000Z",
#       "deleted_at": null,
#       "is_med": false
#     },
#     {
#       "id": 611616,
#       "class_id": 32245,
#       "name": "MIGUEL NARCIZO DE OLIVEIRA NETO",
#       "email": "miguelnarcizo@soaresherdy.com.br",
#       "cpf": null,
#       "address_number": null,
#       "address_cep": null,
#       "address_complement": null,
#       "address": null,
#       "neighborhood": null,
#       "city": null,
#       "state": null,
#       "birthdate": null,
#       "mobile": null,
#       "phone": null,
#       "external_id": "142302916",
#       "created_at": "2024-06-20T12:17:19.000000Z",
#       "deleted_at": null,
#       "is_med": false
#     }
#   ],
#   "first_page_url": "https://app.redacaonline.com.br/api/students?page=1",
#   "from": 1,
#   "last_page": 5,
#   "last_page_url": "https://app.redacaonline.com.br/api/students?page=5",
#   "links": [
#     {
#       "url": null,
#       "label": "&laquo; Anterior",
#       "active": false
#     },
#     {
#       "url": "https://app.redacaonline.com.br/api/students?page=1",
#       "label": "1",
#       "active": true
#     },
#     {
#       "url": "https://app.redacaonline.com.br/api/students?page=2",
#       "label": "2",
#       "active": false
#     },
#     {
#       "url": "https://app.redacaonline.com.br/api/students?page=3",
#       "label": "3",
#       "active": false
#     },
#     {
#       "url": "https://app.redacaonline.com.br/api/students?page=4",
#       "label": "4",
#       "active": false
#     },
#     {
#       "url": "https://app.redacaonline.com.br/api/students?page=5",
#       "label": "5",
#       "active": false
#     },
#     {
#       "url": "https://app.redacaonline.com.br/api/students?page=2",
#       "label": "Próximo &raquo;",
#       "active": false
#     }
#   ],
#   "next_page_url": "https://app.redacaonline.com.br/api/students?page=2",
#   "path": "https://app.redacaonline.com.br/api/students",
#   "per_page": 15,
#   "prev_page_url": null,
#   "to": 15,
#   "total": 64
# }